package com.ppjun.android.smzdm.mvp.model.entity.main
import com.google.gson.annotations.SerializedName



data class NewsInfo(
		@SerializedName("article_id") val articleId: String = "",
		@SerializedName("article_url") val articleUrl: String = "",
		@SerializedName("article_title") val articleTitle: String = "",
		@SerializedName("article_rzlx") val articleRzlx: String = "",
		@SerializedName("article_date") val articleDate: String = "",
		@SerializedName("article_mall") val articleMall: String = "",
		@SerializedName("article_mall_id") val articleMallId: String = "",
		@SerializedName("mall_region") val mallRegion: String = "",
		@SerializedName("article_mall_domain") val articleMallDomain: String = "",
		@SerializedName("article_brand") val articleBrand: String = "",
		@SerializedName("article_brand_id") val articleBrandId: String = "",
		@SerializedName("user_smzdm_id") val userSmzdmId: String = "",
		@SerializedName("article_anonymous") val articleAnonymous: Boolean = false,
		@SerializedName("article_referrals") val articleReferrals: String = "",
		@SerializedName("article_avatar") val articleAvatar: String = "",
		@SerializedName("article_format_date") val articleFormatDate: String = "",
		@SerializedName("article_pic") val articlePic: String = "",
		@SerializedName("article_small_pic") val articleSmallPic: String = "",
		@SerializedName("article_format_pic") val articleFormatPic: String = "",
		@SerializedName("article_collection") val articleCollection: String = "",
		@SerializedName("article_comment") val articleComment: String = "",
		@SerializedName("article_favorite") val articleFavorite: String = "",
		@SerializedName("article_price") val articlePrice: String = "",
		@SerializedName("article_category_last") val articleCategoryLast: String = "",
		@SerializedName("article_filter_content") val articleFilterContent: String = "",
		@SerializedName("article_wap_content") val articleWapContent: String = "",
		@SerializedName("article_wxapp_content") val articleWxappContent: String = "",
		@SerializedName("article_category_ga") val articleCategoryGa: String = "",
		@SerializedName("article_content_img_list") val articleContentImgList: List<String> = listOf(),
		@SerializedName("article_comment_open") val articleCommentOpen: String = "",
		@SerializedName("article_link_type") val articleLinkType: String = "",
		@SerializedName("article_link_list") val articleLinkList: List<Any> = listOf(),
		@SerializedName("share_title") val shareTitle: String = "",
		@SerializedName("share_title_other") val shareTitleOther: String = "",
		@SerializedName("share_pic_title") val sharePicTitle: String = "",
		@SerializedName("share_pic") val sharePic: String = "",
		@SerializedName("b_share_title") val bShareTitle: String = "",
		@SerializedName("share_title_separate") val shareTitleSeparate: String = "",
		@SerializedName("share_long_pic_title") val shareLongPicTitle: String = "",
		@SerializedName("share_reward") val shareReward: String = "",
		@SerializedName("hot_comments") val hotComments: List<Any> = listOf(),
		@SerializedName("relate_youhui") val relateYouhui: List<RelateYouhui> = listOf(),
		@SerializedName("display_mode") val displayMode: String = "",
		@SerializedName("article_tag") val articleTag: String = "",
		@SerializedName("share_wxapp_url") val shareWxappUrl: String = ""
)

data class RelateYouhui(
		@SerializedName("article_id") val articleId: String = "",
		@SerializedName("article_channel_id") val articleChannelId: String = "",
		@SerializedName("article_pic") val articlePic: String = "",
		@SerializedName("article_title") val articleTitle: String = "",
		@SerializedName("article_price") val articlePrice: String = "",
		@SerializedName("article_date") val articleDate: String = "",
		@SerializedName("article_comment") val articleComment: String = "",
		@SerializedName("article_worthy") val articleWorthy: String = "",
		@SerializedName("article_unworthy") val articleUnworthy: String = "",
		@SerializedName("article_worthy_percent") val articleWorthyPercent: String = "",
		@SerializedName("article_mall") val articleMall: String = "",
		@SerializedName("article_is_timeout") val articleIsTimeout: String = "",
		@SerializedName("article_is_sold_out") val articleIsSoldOut: String = "",
		@SerializedName("article_tag") val articleTag: String = "",
		@SerializedName("type") val type: String = "",
		@SerializedName("data_type") val dataType: String = "",
		@SerializedName("article_channel_type") val articleChannelType: String = "",
		@SerializedName("trace_id") val traceId: String = "",
		@SerializedName("rs_id1") val rsId1: String = "",
		@SerializedName("rs_id2") val rsId2: String = "",
		@SerializedName("rs_id3") val rsId3: String = "",
		@SerializedName("rs_id4") val rsId4: String = "",
		@SerializedName("rs_id5") val rsId5: String = ""
)

